---
title: "02_clean"
format: html
---

```{r}
library("tidyverse")
library("here")
library("purrr")
# library("GGally")
```

## Load data

```{r}
meta_path <- here("data/01_dat_meta_load.csv")
feat_path <- here("data/01_dat_feature_load.csv")

meta_df <- read_csv(meta_path, show_col_types = FALSE)
feature_df <- read_csv(feat_path, show_col_types = FALSE)
```

## Neurotransmitter metadata
Inspect the metadata without the 3D structure url and subunit structure.
```{r}
meta_df <- meta_df |> select(-`3D_Structure_URL`, 
                               -`Subunit_Structure`)

meta_df |> head()
```

Then, look at what organisms our data comes from.
```{r}
meta_df |> 
  count(Organism, name = "value") |> 
  ggplot(aes(x = "", y = value, fill = Organism)) +
    geom_col(width = 1) +
    coord_polar(theta = "y") +
    scale_fill_viridis_d(option = "turbo") +
    theme_void()
```


## Neurotransmitter features
Separate feature into the 20 amino acids (aa) and rest (rest).
```{r}
feature_df |> head()
feature_aa <- feature_df %>% select(starts_with("aa_"))
feature_rest <- feature_df %>% select(-starts_with("aa_"))

feature_aa |> head()
feature_rest |> head()
```


```{r, warning=FALSE, message=FALSE}
# feature_rest |> ggpairs() + scale_x_log10() + scale_y_log10()
# feature_aa |> ggpairs() + scale_x_log10() + scale_y_log10()
```

