---
title: "03_prediction"
format: html
---


Loading libraries

```{r}
library("tidyverse")
library("here")
library("tidymodels")


```


loading data 
```{r}
meta_path <- here("data/01_dat_meta_load.csv")
feat_path <- here("data/01_dat_feature_load.csv")

meta_df <- read_csv(meta_path, show_col_types = FALSE)
feature_df <- read_csv(feat_path, show_col_types = FALSE)

```
baldas 

```{r}
meta_df
```


```{r}
feature_df
```
defining two classes. Based on Knlowedge provided by Ãkos, we will spit the receptors into 3 classes: Glutamate, Ionotropic and Cysloop receptors. It would be interesting to see if we can predict the class from AA composition.
Todo this we first add a new column to the meta df called "class".

```{r}
meta_with_classes <- meta_df |> 
    mutate(
      receptor_class = case_when(
          str_detect(Protein_Name, "Glutamate") ~ "Glutamate",
          str_detect(Protein_Name, "Ionotropic")  ~ "Ionotropic",
          TRUE       ~ "CysLoop"
  )
)

meta_with_classes
```


